services:
    sumitomotool-front-nginx:
        container_name: sumitomotool-front-nginx
        restart: unless-stopped
        image: nginx:1.27
        volumes:
            - ./:/var/www
            - ./docker/nginx/${VHOST_FILE}:/etc/nginx/conf.d/custom.conf
        ports:
            - "80"
        links:
            - sumitomotool-front-node
        environment:
            VIRTUAL_HOST: ${DOMAIN_HOSTS}
            VIRTUAL_PORT: 80
            LETSENCRYPT_HOST: ${DOMAIN_HOSTS}
            LETSENCRYPT_EMAIL: ${DOMAIN_EMAIL}
        networks:
            - nginx-proxy
            - sumitomotool

    sumitomotool-front-node:
        container_name: sumitomotool-front-node
        user: ${USER_ID}:${GROUP_ID}
        build:
            context: ./
            dockerfile: docker/node/local/Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                APP_USER: ${APP_USER}
        volumes:
            - ./:/app
        restart: unless-stopped
        networks:
            - sumitomotool

networks:
    sumitomotool:
    nginx-proxy:
        external: true
